#!/bin/bash
ARGS=$*
TIMESTAMP=`date +"%Y-%m-%d--%Hh%Mm%Ss"`
FILENAME="unknown"
DIR=`dirname $0`

if [[ "${ARGS}" =~ (^|.*[/[:space:]\\=])([[:alnum:]_-]+\.php).* ]]
then
  FILENAME=${BASH_REMATCH[2]}
fi

echo '        ____  __                __'
echo '       / __ \/ /_  ____  ____  / /_____ ___'
echo '   -- / /_/ / __ \/ __ `/ __ \/ __/ __ `__ \  --'
echo '  -- / ____/ / / / /_/ / / / / /_/ / / / / / --'
echo ' -- /_/   /_/ /_/\__,_/_/ /_/\__/_/ /_/ /_/ --'
echo ' '
scala -classpath $DIR/builds/phantm.jar:$DIR/lib/cup/dist/java-cup-11a-runtime.jar phantm.Main --maindir $DIR/  $* 2>&1 | tee ${FILENAME}--${TIMESTAMP}.out | tee last.out | less -eRFEX
