#!/bin/bash
ARGS=$*
TIMESTAMP=`date +"%Y-%m-%d--%Hh%Mm%Ss"`
FILENAME="unknown"
DIR=`dirname $0`

if [[ "${ARGS}" =~ (^|.*[/[:space:]\\=])([[:alnum:]_-]+\.php).* ]]
then
  FILENAME=${BASH_REMATCH[2]}
fi

echo '        ____  __                __'
echo '       / __ \/ /_  ____  ____  / /_____ ___'
echo '   -- / /_/ / __ \/ __ `/ __ \/ __/ __ `__ \  --'
echo '  -- / ____/ / / / /_/ / / / / /_/ / / / / / --'
echo ' -- /_/   /_/ /_/\__,_/_/ /_/\__/_/ /_/ /_/ --'
echo ' '
scala29 -classpath $DIR/target/scala-2.9.2/classes/:$DIR/lib/cup2-scala.jar:$DIR/lib/cup2.jar phantm.Main  $* 2>&1 | tee ${FILENAME}--${TIMESTAMP}.out | tee last.out
